# Generated by Django 2.2.24 on 2022-07-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20220702_1652'),
    ]

    operations = [
    ]
