# Generated by Django 2.2.24 on 2022-07-03 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20220702_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owners_normalized_phonenumner',
            new_name='owner_pure_phone',
        ),
    ]
