# Generated by Django 2.2.24 on 2022-07-03 06:48

from django.db import migrations


def connect_flats_with_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        owner, created = Owner.objects.get_or_create(
            full_name=flat.owner_full_name,
            pure_phone_number=flat.owner_pure_phone)
        owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20220703_1202'),
    ]

    operations = [
        migrations.RunPython(connect_flats_with_owners)
    ]
