# Generated by Django 2.2.24 on 2022-07-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20220703_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner_full_name',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
