# Generated by Django 2.2.24 on 2022-07-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_auto_20220705_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='like',
            new_name='likes',
        ),
    ]
